Imports and setup

In [24]:
import pandas as pd
import numpy as np
import re

Create dataframe to make a correlation table out of

In [25]:


df = pd.DataFrame(pd.read_csv('cleaned_data_file copy 2.csv', sep=","))

cols = ['Case', 'Involved', 'Dead', 'Wounded', 'Vehicles', 'Address', 'Type',
       'Involved_lightmover', 'Involved_pedestrian', 'Involved_passenger',
       'Involved_offroad_vehicle', 'Involved_elderly', 'Involved_busdriver',
       'Involved_truckdriver', 'Involved_public_transport_driver',
       'Involved_car_driver', 'Involved_motorbike_driver',
       'Involved_moped_driver', 'Involved_biker', 'Involved_minor',
       'Involved_not_wore_seatbelt', 'Involved_learner_driver',
       'Involved_vehicle_driver', 'Road_type', 'Feature', 'Curvature',
       'Levelness', 'Road_condition', 'Surface_condition', 'Speed_limit',
       'Weather', 'Lighting', 'Latitude', 'Longitude', 'Date', 'Time']


for c in cols:
    print(df[c].value_counts(normalize=False, dropna=False))
    print()

2.000140e+12    1
3.100211e+12    1
3.100211e+12    1
3.100211e+12    1
3.100211e+12    1
               ..
3.100180e+12    1
3.100180e+12    1
3.100180e+12    1
3.100180e+12    1
1.111180e+12    1
Name: Case, Length: 14028, dtype: int64

2.0     7531
1.0     4079
3.0     1484
4.0      454
5.0      180
0.0      163
6.0       65
7.0       34
8.0       13
10.0       7
9.0        6
11.0       3
13.0       3
24.0       2
15.0       1
19.0       1
14.0       1
22.0       1
Name: Involved, dtype: int64

0.0    13389
1.0      602
2.0       27
3.0        8
4.0        2
Name: Dead, dtype: int64

1.0     11320
2.0      1566
0.0       466
3.0       417
4.0       142
5.0        69
6.0        22
7.0         7
9.0         5
8.0         3
11.0        2
20.0        2
23.0        1
10.0        1
19.0        1
13.0        1
14.0        1
12.0        1
22.0        1
Name: Wounded, dtype: int64

1.0    7448
2.0    5025
3.0     891
0.0     431
4.0     169
5.0      45
6.0      15
7.0       3
9.0       1
Name: Vehicles, dtype: int64

 Harju maakond Tallinn Kesklinna linnaosa Pärnu mnt       199
 Harju maakond Tallinn Kesklinna linnaosa Narva mnt       161
 Harju maakond Saue vald                                  157
 Harju maakond Tallinn Haabersti linnaosa Paldiski mnt    142
 Harju maakond Tallinn Lasnamäe linnaosa Peterburi tee    135
                                                         ...
 Lääne-Viru maakond Vinni vald Kantküla                     1
 Pärnu maakond Pärnu linn Pärnu linn Raja tn                1
 Tartu maakond Tartu vald Möllatsi küla                     1
 Pärnu maakond Häädemeeste vald Laadi küla Pihla tee        1
 Harju maakond Nissi vald Jaanika küla                      1
Name: Address, Length: 3631, dtype: int64

Kokkupõrge jalakäijaga               3276
Kokkupõrge sõidukiga küljelt         2670
Sõiduki teelt väljasõit              2047
Kokkupõrge vastutuleva sõidukiga     1054
Kokkupõrge ees liikuva sõidukiga      978
Sõiduki ümberpaiskumine teel          966
Kokkupõrge teevälise takistusega      824
Muu liiklusõnnetus                    611
Kokkupõrge ees seisva sõidukiga       538
Kukkumine ühissõidukis                459
Sõidukite külgkokkupõrge              260
Kokkupõrge loomaga                    160
Kokkupõrge teel oleva takistusega     107
Teadmata                               78
Name: Type, dtype: int64

0.0    13809
1.0      219
Name: Involved_lightmover, dtype: int64

0.0    10651
1.0     3377
Name: Involved_pedestrian, dtype: int64

0.0    10447
1.0     3581
Name: Involved_passenger, dtype: int64

0.0    13937
1.0       91
Name: Involved_offroad_vehicle, dtype: int64

0.0    12403
1.0     1625
Name: Involved_elderly, dtype: int64

0.0    13242
1.0      786
Name: Involved_busdriver, dtype: int64

0.0    12582
1.0     1446
Name: Involved_truckdriver, dtype: int64

0.0    13095
1.0      933
Name: Involved_public_transport_driver, dtype: int64

1.0    10088
0.0     3940
Name: Involved_car_driver, dtype: int64

0.0    13100
1.0      928
Name: Involved_motorbike_driver, dtype: int64

0.0    13511
1.0      517
Name: Involved_moped_driver, dtype: int64

0.0    11919
1.0     2109
Name: Involved_biker, dtype: int64

0.0    11644
1.0     2384
Name: Involved_minor, dtype: int64

0.0    12431
1.0     1597
Name: Involved_not_wore_seatbelt, dtype: int64

0.0    12860
1.0     1168
Name: Involved_learner_driver, dtype: int64

1.0    12351
0.0     1677
Name: Involved_vehicle_driver, dtype: int64

Tänav                    7746
Põhimaantee              1885
Kõrvalmaantee            1493
Tugimaantee              1103
Kohalik maantee           408
Muu koht                  318
Õuealatee                 283
Jalg- ja jalgrattatee     258
Parkla                    163
NaN                       110
Jalgtee                   109
Jalgrattatee               60
Väljak                     40
Metsatee                   30
Eramaantee                 17
Ramp, ühendustee            5
Name: Road_type, dtype: int64

Erielemendita teelõik    8344
Ristmik                  4294
Muu ristumine             589
NaN                       446
Kergliiklustee            188
Muu koht                  103
Parkla                     64
Name: Feature, dtype: int64

Sirge tee     11610
Lauge kurv     1643
Järsk kurv      393
NaN             382
Name: Curvature, dtype: int64

Tasane tee      12564
Kerge langus      600
Kerge tõus        409
NaN               320
Järsk langus       81
Järsk tõus         28
Tõusu hari         26
Name: Levelness, dtype: int64

Sõidutee on korras                                                                      11922
Sõidutee on libe                                                                         1438
NaN                                                                                       271
Sõidutee on ebatasane                                                                     259
Nähtavus on piiratud                                                                       66
Teekattemärgistus puudub                                                                   24
Puu (post) teepeenral (eraldusribal)                                                       15
Sõidutee kitseneb                                                                           7
Sõiduteel on takistus                                                                       6
Teepeenar on halvas seisukorras                                                             5
Ohtliku koha tähistus puudub                                                                4
Liiklusmärk puudub, ei ole nähtav                                                           4
Foor ei tööta, ei ole nähtav                                                                4
Teeremondikoha tähistus on puudulik                                                         1
Foor ei tööta, ei ole nähtav,Sõidutee on libe                                               1
Nähtavus on piiratud,Sõidutee on ebatasane,Sõidutee on libe,Teekattemärgistus puudub        1
Name: Road_condition, dtype: int64

Kuiv                                            8751
Märg                                            3470
Lumelörts, soolalumine segu                      478
NaN                                              228
Töötlemata pinnaga jäätunud märg kate, jäide     183
Töödeldud pinnaga jäätunud kate                  172
Kohev lahtine lumi                               164
Sõidujäljed puhtad, sõidujälgede vahe lumine     130
Töötlemata pinnaga kinnisõidetud lumi            127
Töötlemata pinnaga jäätunud kuiv kate            127
Töödeldud pinnaga kinnisõidetud lumi             114
Pori, saaste                                      84
Name: Surface_condition, dtype: int64

50.0     7583
90.0     3655
70.0      840
30.0      660
20.0      431
NaN       408
40.0      206
110.0     124
60.0       55
10.0       18
100.0      15
80.0       12
25.0        8
45.0        5
5.0         5
120.0       2
15.0        1
Name: Speed_limit, dtype: int64

Selged olud                  6788
Pilvised olud                5503
Vihmasadu                     721
Lumised olud                  458
NaN                           233
Madal vastu paistev päike     204
Udused olud                    93
Tuisune või tormine            28
Name: Weather, dtype: int64

Valge aeg                        9903
Pimeda ajal valgustus põleb      2361
Pimeda ajal valgustus puudub     1284
Pimeda ajal valgustus ei põle     268
NaN                               212
Name: Lighting, dtype: int64

59.373991    17
59.427072    16
58.886938    14
59.440550    13
58.973775    13
             ..
59.431828     1
58.815094     1
59.453314     1
58.352740     1
58.353400     1
Name: Latitude, Length: 13355, dtype: int64

27.875295    17
24.742738    16
25.569928    14
24.785646    13
25.960528    13
             ..
26.270162     1
26.548752     1
24.703933     1
22.510753     1
25.573435     1
Name: Longitude, Length: 13355, dtype: int64

15.06.2013    15
12.08.2021    15
03.06.2021    13
16.05.2021    13
30.05.2020    13
              ..
12.11.2017     1
26.01.2021     1
18.11.2017     1
20.11.2017     1
28.03.2017     1
Name: Date, Length: 3603, dtype: int64

00:00    96
17:00    86
16:30    76
13:00    75
17:30    74
         ..
02:51     1
04:46     1
03:26     1
04:39     1
02:39     1
Name: Time, Length: 1391, dtype: int64

In [26]:

def makeUnique(original_df, correlation_dataframe, column_name):
    # extract the unique values from the Surface_condition column
    unique_values = original_df[column_name].unique()

    # create a new dataframe with as many columns as there are unique values in the Surface_condition column
    # and the same number of rows as the original dataframe
    new_df = pd.DataFrame(columns=unique_values, index=original_df.index)

    # iterate over the rows of the original dataframe
    for i, row in original_df.iterrows():
        # set the corresponding cell in the new dataframe to 1 if the row has the value for that column,
        # and 0 otherwise
        for line in unique_values:
            new_df.loc[i, line] = 1 if row[column_name] == line else 0

    # join the new dataframe with the original dataframe to create a single dataframe
    correlation_dataframe = correlation_dataframe.join(new_df)

    # print the resulting dataframe
    return correlation_dataframe


corr_df = df[['Involved', 'Dead', 'Wounded']]

#'Road_type', 'Feature', 'Curvature', 'Levelness', 'Road_condition', 'Surface_condition', 'Speed_limit','Weather', 'Lighting',

corr_df = makeUnique(df, corr_df, 'Road_type')

#corr_df = makeUnique(df, corr_df, 'Feature')

# corr_df = makeUnique(df, corr_df, 'Curvature')

# corr_df = makeUnique(df, corr_df, 'Levelness')

# corr_df = makeUnique(df, corr_df, 'Road_condition')

# corr_df = makeUnique(df, corr_df, 'Surface_condition')

# corr_df = makeUnique(df, corr_df, 'Weather')

# corr_df = makeUnique(df, corr_df, 'Lighting')

corr_df.head()

,Involved,Dead,Wounded,Tänav,Tugimaantee,Põhimaantee,Parkla,Väljak,Kõrvalmaantee,Kohalik maantee,Metsatee,Õuealatee,Muu koht,Jalg- ja jalgrattatee,Jalgtee,Jalgrattatee,NaN,"Ramp, ühendustee",Eramaantee
0,2.0,0.0,1.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2.0,0.0,1.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2.0,0.0,1.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,2.0,0.0,2.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,2.0,0.0,1.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

Generate graph

In [30]:
# compute the pairwise correlations between all columns in the dataframe
corr_matrix = corr_df.corr()

corr_matrix

C:\Users\Robert\AppData\Local\Temp\ipykernel_17372\1774013459.py:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  corr_matrix = corr_df.corr()

          Involved      Dead   Wounded
Involved  1.000000  0.055405  0.568024
Dead      0.055405  1.000000 -0.145478
Wounded   0.568024 -0.145478  1.000000